[model]
"sample_num" = 1024
"radius" = 0.3
"neighbor_num" = 20
"out_channels" = 512
"nhead" = 8
"num_layers" = 4
"point_num" = 512

[train]
"batch_size" = 12
"epochs" = 100
"lr" = 1e-4
"weight_decay" = 0.05

[loss]
"alpha" = 1
"beta" = 1
"gamma" = 1
"theta" = 10
