[model]
"point_num" = 4096
"fps_sample_num" = 1024
"ball_radius" = 0.3
"ball_neighbor_num" = 20
"contact_sample_num" = 512
"gather_neighbor_num" = 100
"feature_dim" = 128
"head_num" = 8
"layer_num" = 6

[train]
"batch_size" = 12
"epochs" = 100
"lr" = 1e-4

[loss]
"alpha" = 1
"beta" = 1
"gamma" = 1
"theta" = 10
